//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatewayForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GatewayForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000D6F000C68DF02.
        /// </summary>
        internal static string ADDRESS_NODE {
            get {
                return ResourceManager.GetString("ADDRESS_NODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datastore.sqlite.
        /// </summary>
        internal static string DATABASE_NAME {
            get {
                return ResourceManager.GetString("DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLGATEWAY.
        /// </summary>
        internal static string DATABASE_TABLENAME {
            get {
                return ResourceManager.GetString("DATABASE_TABLENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data from field required .
        /// </summary>
        internal static string ERROR_SEARCH_DATABASE {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon__1_ {
            get {
                object obj = ResourceManager.GetObject("favicon__1_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_led2 {
            get {
                object obj = ResourceManager.GetObject("green_led2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_seldat {
            get {
                object obj = ResourceManager.GetObject("icon_seldat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ds.
        /// </summary>
        internal static string NODE_MAC {
            get {
                return ResourceManager.GetString("NODE_MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_led {
            get {
                object obj = ResourceManager.GetObject("red_led", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_led2 {
            get {
                object obj = ResourceManager.GetObject("red_led2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \DataStore.
        /// </summary>
        internal static string SELDAT_DATABASE {
            get {
                return ResourceManager.GetString("SELDAT_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \DataStore\Excel.
        /// </summary>
        internal static string SELDAT_EXCEL_DATASTORE {
            get {
                return ResourceManager.GetString("SELDAT_EXCEL_DATASTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GATEWAY DATA.
        /// </summary>
        internal static string SELDAT_EXCEL_TITLE {
            get {
                return ResourceManager.GetString("SELDAT_EXCEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seldat_icon {
            get {
                object obj = ResourceManager.GetObject("seldat_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UCAST.
        /// </summary>
        internal static string UCAST_HEADER {
            get {
                return ResourceManager.GetString("UCAST_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT+UCASTB:.
        /// </summary>
        internal static string ZIGBEE_BINARY {
            get {
                return ResourceManager.GetString("ZIGBEE_BINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT+UCAST:.
        /// </summary>
        internal static string ZIGBEE_SEND {
            get {
                return ResourceManager.GetString("ZIGBEE_SEND", resourceCulture);
            }
        }
    }
}
